<?php

require_once dirname(__FILE__) . '/../Anagrams.php';

/**
 * Test class for Anagrams.
 * Generated by PHPUnit on 2012-01-03 at 16:31:37.
 */
class AnagramsTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Anagrams
	 */
	protected $anagramObj;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->anagramObj = new Anagrams('../dictionary.txt');
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	public function testWordAnz() {
		$this->assertCount(6, $this->anagramObj->getWords());
	}
	
	public function testAnagramsOfWord() {
		$this->assertEquals('toto', $this->anagramObj->getAnagram('otto'));
	}
	
	public function testCompareWords() {
		$this->assertTrue($this->anagramObj->compareWords('otto','otto'));
		$this->assertTrue($this->anagramObj->compareWords('otto','toot'));
		$this->assertTrue($this->anagramObj->compareWords('actaeonidae','donatiaceae'));
	}
	
}

?>
